name:                hitomezashi
version:             0.1.0.0
github:              "atavixion/hitomezashi"
license:             BSD-3-Clause
author:              "Julian Mac Kenzie"
maintainer:          "jukiangm@gmail.com"
copyright:           "2023 Julian Mac Kenzie"

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/atavixion/hitomezashi#readme>

dependencies:
- base >= 4.7 && < 5
- hip
- optparse-applicative
- bytestring
- ansi-wl-pprint

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints
- -threaded

library:
  source-dirs: src

executables:
  hitomezashi-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hitomezashi

tests:
  hitomezashi-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hitomezashi
